### ISSUE TITLE
Build fails due to missing kustomize

### ISSUE THREAD

**Issue by janhoy** [bloomberg/solr-operator#101]
**Describe the bug**
Following the README to setup my first operator, `make install deploy` fails with:

    [...snip...]
    kustomize build config/crd > helm/solr-operator/crds/crds.yaml
    /bin/sh: kustomize: command not found
    make: *** [manifests] Error 127

**To Reproduce**
1. `make install deploy` on a clean Mac system with Docker Desktop and Go installed
2. See above error

**Expected behavior**
Build succeeds

**Environment (please complete the following information):**
 - macOS 10.15.3
 - Docker Desktop 2.2.0.4 with Kubernetes
 - Go 1.14 installed via brew

**Additional context**

**Comment by janhoy** [comment]
My solution was `brew install kustomize`

**Comment by HoustonPutman** [comment]
Hey Jan, glad to see you here!

So before working on the operator, you should run `./hack/install_dependencies.sh`. Checked through the Readme, and I didn't see it mentioned there. I'll add it as a part of the instructions.
