### ISSUE TITLE
Better turorial for getting started

### ISSUE THREAD

**Issue by janhoy** [bloomberg/solr-operator#105]
**Is your feature request related to a problem? Please describe.**
I got stuck several times in setting up the operator, as the README goes straight into building from source and it is a bit unclear what happens.

**Describe the solution you'd like**
The first steps in README should not be building it from source but installing with as few steps as possible, whether using helm or directly with `kubectl apply` some combined yaml that gets everything setup (like for dependencies)

So when testing this out for myself, I created kind of a tutorial that is what I'd like to have seen when visiting the repo myself. It takes you through setting up your environment (Mac only) with ingress controller, k8s dashboard and Solr install, scale, upgrade and delete. The tutorial is in this gist, feel free to steal it or parts of it into a Wiki page or something in this repo.

https://gist.github.com/19bd70ab4ecbcc35eeaecfbc63fbbe1c

**Comment by HoustonPutman** [comment]
This is awesome. The readme has basically been made from my perspective, which is definitely the wrong way to go about it. I think this is an opportune time to shorten the readme and make it more geared towards new users. We can then move a lot of other content into more specific documentation files.

I can start on something this weekend and make a PR. Thanks so much for getting this started, it's long overdue.
