### ISSUE TITLE
The operator uses a LB endpoint to connect to ZK

### ISSUE THREAD

**Issue by janhoy** [bloomberg/solr-operator#106]
**Describe the bug**
Operator uses the service-name as connection string to zk. The recommended way is to list each individual zk host:port in the connection string so Solr's zk client is able to detect a failing host and reconnect to another.

Not sure what exactly is the consequence of using the LB address, but from Solr's point of view it believes it has only one zk host. It **may** also mean that in case of a connection loss that Solr will fail since it believes it has no other nodes to try???

**To Reproduce**
This always happens. Going to Solr's Admin UI -> Cloud -> Zk Status will then show errors that there is a mismatch between the connection string and how many followers are reported by the zk node.

See also related https://issues.apache.org/jira/browse/SOLR-14371 which attempts to make the zk status screen introspect the zk cluster config and show better error messages.

**Expected behavior**
Unless and until Solr supports reconfiguring its zk clients based on zk dynamic reconfig, I believe the Operator should enumerate all ZK hosts in ZK_HOST connection string.

**Comment by HoustonPutman** [comment]
This is definitely do-able. Honestly since we don't have a range of supported Solr versions, the load balancer should never have been used in the first place since Solr 7 and before don't support Zookeeper 3.5+

**Comment by janhoy** [comment]
I’m not saying it won’t work, perhaps even there are benefits in case of k8s killing zk’s and staring new pods with new IP addresses? But I think it is worth to do some failure case testing just to be sure.

**Comment by HoustonPutman** [comment]
This is no longer the case as of #138. This issue can be closed.
