### ISSUE TITLE
Remove support for etcd/zetcd

### ISSUE THREAD

**Issue by HoustonPutman** [bloomberg/solr-operator#117]
The Zookeeper Operator is much more mature now, and there is less of a need to have support for etcd/zetcd. The code is more complex, and if no one is using it, it would be easier to remove the options all together.

It will also allow us to make the CRD spec more intuitive.

If there is significant use though, I'll close the issue.

**Comment by sepulworld** [comment]
Good call! I agree, zk operator works well. Probably no need to support etcd
