### ISSUE TITLE
Solr image pull policy cannot not be specified

### ISSUE THREAD

**Issue by dalbani** [bloomberg/solr-operator#136]
**Is your feature request related to a problem? Please describe.**
I'm developing and using my own Solr images for my SolrCloud cluster.
It means regularly (re)deploying containers with the _latest_ image tag.
Except on production where I naturally deploy specific versions which don't need to be pulled if already present.
That's actually the default behavior of Kubernetes when `imagePullPolicy` is omitted altogether: https://kubernetes.io/docs/concepts/configuration/overview/#container-images
But strangely enough, there's no way to _explicitly_ choose this behavior.
So when I define my SolrCloud resource, what am I supposed to fill `pullPolicy` with:
```
kind: SolrCloud
spec:
  solrImage:
    repository: my.repo.com/my-solr
    tag: latest   # or can be 1.0.0 for example
    pullPolicy: ??
```
Not setting it means that the default `IfNotPresent` is then used: https://github.com/bloomberg/solr-operator/blob/master/api/v1beta1/solrcloud_types.go#L31.
Which is obviously not what I want with `latest`-based deployments.

**Describe the solution you'd like**
A simple way to actually explicitly omit the `imagePullPolicy` for containers in the stateful set.

**Describe alternatives you've considered**
Given that I deploy the `SolrCloud` resource with a home-made Helm chart, I suppose that I could write a helper function to look at the image tag (`latest` or not) and return an `imagePullPolicy` or not.

**Comment by HoustonPutman** [comment]
Thanks for the excellently detailed and informative issue!

I was not aware that this functionality was available. Should be an easy enough change to not default the pullPolicy.

+1 from me.
