### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by daafgo** [bloomberg/solr-operator#166]
Hello everybody, I'm trying to secure the access to my cloud but I didn't see anything of how to do it, I tried to follow the official documentation but it not works, maybe I missing something?
https://lucene.apache.org/solr/guide/8_7/basic-authentication-plugin.html#basic-authentication-plugin

**Comment by HoustonPutman** [comment]
Can you expand on the steps you did to enable the authentication?

There is a line on how to enable with SolrCloud, not standalone Solr. Did you do that to upload the security file to ZK?

**Comment by daafgo** [comment]
Yes but when I send the file to ZK the solrCloud explodes, I'm gonna try in another way

**Comment by hartmut-co-uk** [comment]
Hi, were you able to resolve?
