### ISSUE TITLE
Support the Ability to tune GC_TUNE and SOLR_OPTS

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#32]
**Is your feature request related to a problem? Please describe.**
Ability to tune SOLR_OPTS and GC_TUNE, related docs
https://lucene.apache.org/solr/guide/8_1/taking-solr-to-production.html#memory-and-gc-settings
https://lucene.apache.org/solr/guide/8_1/taking-solr-to-production.html#override-settings-in-solrconfig-xml

**Describe the solution you'd like**
When going to production these values require tuning typically. Allow for the Solr-Operator SolrCloud CRD the ability to tune values passed to these ENV variables for Solr Cloud process to use.

Im starting work on this now. If you have any feedback or suggestions @HoustonPutman let me know! should be straightforward though.

**Comment by timterle** [comment]
Hi, I'm also also interested in the ability to tweak the solr arguments.

We are thinking about creating our own solr image based on the official one and do some special work in the entrypoint based on some custom environment variables. So we'd like to be able to specify any environment variable.

Would it be possible to just have an "env" variable that can include any key/value mapping?

**Comment by sepulworld** [comment]
Thanks for the feedback @timterle. Yes, this is probably possible, and would offer more flexibility in long run. I will take a look

**Comment by HoustonPutman** [comment]
Support for custom Env variables was added in #74 !
