### ISSUE TITLE
Enable configuring of hostname generation and ports

### ISSUE THREAD

**Issue by timterle** [bloomberg/solr-operator#36]
**Is your feature request related to a problem? Please describe.**
We aim to run Solr in Amazon EKS (managed Kubernetes). We have microservices in an Amazon VPC that wants to communicate with Solr and Zookeeper running in a Kubernetes cluster that belongs to the same VPC. Amazon EKS exposes pod IPs in the VPC, but not service IPs. So our microservices (outside of Kubernetes but in the same VPC) can only talk to Solr pods, not Solr services. The Solr Operator can't easily be configured to enable this use-case.

**Describe the solution you'd like**
Possibility to configure template like expression for hostnames: {{ .Name }}.{{ .Namespace }}.ourdomain.com
Possibility to configure service port. It's now hardcoded to 80.

**Additional context**
By using ExternalDNS (https://github.com/kubernetes-incubator/external-dns) and annotating the Solr and Zookeeper headless services we can get Solr and Zookeeper pod IPs (VPC IPs, not Kubernetes internal IPs) registered in DNS (Route53). Our microservices can use these DNS records to talk to Solr pods.

As an example, let's say we create a solrcloud "example" with ingress-base-domain=ourdomain.com, namespace=default, ExternalDNS enabled, the result is then

hosts registered in zookeeper:
  default-example-solrcloud-0.ourdomain.com:80
  default-example-solrcloud-zookeeper-0.ourdomain.com:80
pods:
  example-solrcloud-0 8983
  example-solrcloud-zookeeper-0 8983
services:
  example-solrcloud-0 80
  example-solrcloud-zookeeper-0 80
dns:
  example-solrcloud-0.ourdomain.com
  example-solrcloud-zookeeper-0.ourdomain.com

With the help of ExternalDNS our own microservices can now use example-solrcloud-zookeeper-0.ourdomain.com:2181 as address to zookeeper. It will resolve to the Zookeeper pod IP in the VPC. However, the solrj client will get the state of the cluster from Zookeeper and it says all hosts are prefixed with "default-". So solrj tries to use the hostname default-example-solrcloud-0.ourdomain.com to talk to solr. But this host does not exist in DNS. If it was possible to configure the Solr Operator how the hostnames are generated it would be possible to skip the namespace and generate the same hostnames as ExternalDNS (example-solrcloud-0.ourdomain.com).

With this change our own microservices could now get a working Solr hostname and IP. But this will still not work because the port is wrong. The Solr pods are reachable on port 8983, but Zookeeper will tell the clients that Solr can be reached on port 80 (because that is the internal Kubernetes service port). If it was possible to configure the Solr Operator to have 8983 as the service port rather than 80 this communication would work.

This way the hostname/port is the same for external and internal communication, but they are resolved to pods for external access and services for internal access. We have tested to implement this and it seems to work. No ingresses or loadbalancers are needed.

**Comment by HoustonPutman** [comment]
So I think this would be an awesome addition. We should probably make this a broader addressability configuration feature that lets you select from:

- LoadBalanced Services, services + ingress, or headless service (to possibly use with external DNS?)
- Override the default ports
- Service Annotations for ExternalDNS, and if so what the format of the URL should be? (option to include namespace or not)

A quick question about how you are using ExternalDNS, as I'm just learning about it now. There is a way to scrape kubernetes services using ExternalDNS without the services having annotations, correct? We can definitely add the annotations, but it looks like there is a way to scrape all services using a filter. At that point I think you should be able to do run ExternalDNS with the parameter `--fqdn-template={{.Name}}.{{.Namespace}}.ourdomain.com`, and I think it would probably work with the namespace in the domain... I still need to do some research into the ports though.

I worry about removing the namespace from the external DNS, as there could be conflicts with similarly named solrClouds in different namespaces. I may be overly cautious about that, so for now I've included it in the preliminary list of configuration options above.

**Comment by timterle** [comment]
Currently we annotate the headless solr and zookeeper services.
We are experimenting with not having an ingress-base-domain. If we use ingress-base-domain then that domain must somehow be added to Kubernetes DNS. Can that easily be configured? Prometheus exporter can't resolve example-solrcloud-0.ourdomain.com because ourdomain.com is not in Kubernetes DNS, only in our external DNS (route53). So now we don't use ingress-base-domain. Instead we have a dns zone for each solrcloud with the name solrcloudname-solrcloud-headless.

Yes, namespace in the domain probably works if it's a subdomain, but having it as a prefix to all generated hostnames makes the naming incompatible with the ExternalDNS naming where you can't customize the prefix.

**Comment by timterle** [comment]
What about something like this in solrcloud.yaml?

```
kind: SolrCloud
spec:
  solrServicePort: 8983
  solrFqdnTemplate: {{ .Name }}.{{ .Namespace }}.domain.com
```

**Comment by HoustonPutman** [comment]
Yeah, we should definitely add a spec entry for addressability.

I can probably work on that sometime next week. I'll support Ingress, ExternalDNS, and headless services at first.

**Comment by timterle** [comment]
@HoustonPutman That's great!
Right now we create a headless prometheus exporter service ourselves to get ExternalDNS integration for prometheus. Maybe it would be a good addition as well? Is that included in your work or should I create a new issue for that?

**Comment by HoustonPutman** [comment]
@timterle , sorry for the extremely late reply.

I've started to work on a big overhaul of customization. I've done a lot of reading on ExternalDNS, and I still have a few questions.

- Do you use externalDNS with services that are not loadBalanced? If so I don't see how that works in their documentation, it looks like a Service must be either 1) LoadBalanced 2) ExternalName 3) Headless Node-Port. Our services for the solrcloud are none of those, so I was looking into giving both of following options, which would work together: 1) use LoadBalanced services or and Ingress and 2) Use externalDNS or not.
- Would you be able to use ExternalDNS with ingresses? Because it looks like that is also supported. This is less important if your answer to the previous bullet point is yes.

I'm planning on pushing a PR with the CRD changes I'm proposing before actually implementing the logic. That way we can iterate on features and design without having to do a ton of rewrites. So I'd really appreciate your input, as we run our kube clusters very differently than y'all do.

**Comment by timterle** [comment]
@HoustonPutman it's ok, we are all busy  :)

I don't think NodePort is necessary. It works with ClusterIP as well. This is what we do and it seems to work:

`kubectl annotate svc example-solrcloud-zookeeper-headless external-dns.alpha.kubernetes.io/hostname=domain.com`

**Comment by HoustonPutman** [comment]
Finally got it merged in @timterle ! Sorry it took this long, but I really think we got it right.

If you still use the Solr Operator and ExternalDNS mind testing it out at some point? (I'd love for someone to test it out before we do a release.)
