### ISSUE TITLE
Unable to create a SolrCloud and specify a chRoot in ZK for it

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#61]
**Describe the bug**
We should be able to use a zk-operator generated zk cluster and specify what chRoot to use for the solrcloud (I would like to not use '/' but perhaps use '/{name_of_cloud}'

**To Reproduce**
Stand by, Ill post the test yamls I have tried to use unsuccessfully

**Expected behavior**
ZK_HOST/<custom_chroot>

**Comment by HoustonPutman** [comment]
Yeah, this should be super easy to do. We also need to fix a bug that Solr expects the chRoot path to exist when it starts up. If the path doesn't exist, Solr fails to start correctly.

**Comment by HoustonPutman** [comment]
Made a fix for this issue. But it won't really be usable until we also add a fix for making sure that the chRoot exists before starting the stateful set.

**Comment by HoustonPutman** [comment]
Resolved in #62 . ChRoot option is available for all ZK Reference types. Validation/Creation is done for all uses of a chRoot.
