### ISSUE TITLE
Complications around readinessChecks and pod restarts

### ISSUE THREAD

**Issue by HoustonPutman** [bloomberg/solr-operator#66]
There is a chicken/egg problem with restarting SolrCloud pods.

- We need to be able to connect to a pod in order to do any necessary recovery of replicas contained on that Solr Node. Therefore the Service for that node needs to point to the pod.
- We need to ensure that a rolling restart of the StatefulSet does not start on the next pod until all replicas are healthy in the pod. The only way we can do that through the provided statefulSet mechanisms is through a robust `readinessCheck`.

So if we want both of these to be true, then the SolrNode services (both individual node services, and the headless service) need to route to pods regardless of whether that node is _ready_ or not. This can be achieved by using the following option:

```yaml
Service:
  Spec:
    PublishNotReadyAddresses: true
```

**Comment by HoustonPutman** [comment]
Follow this ticket for a better status handler for Solr. https://issues.apache.org/jira/browse/SOLR-14210?filter=-3

Knowing that this will only work for certain versions of Solr (8.5+), we will likely need to have a parameter to allow for disabling of this check for unsupported Solr versions.

**Comment by janhoy** [comment]
What happens with e.g. a version upgrade if there is only one pod? Downtime?
Or if there are multiple pods, but a collection has `replicationFactor=1` - will that collection be unavailable during upgrade? Or some magic that increases rf during upgrade?

**Comment by janhoy** [comment]
This will be released in 8.6. The new parameter is `/api/node/health?requireHealthyCores=true`. On pre-8.6 versions, adding this parameter will not throw an error, but the health check will return OK even if cores are recovering.

**Comment by HoustonPutman** [comment]
yes, we should definitely add that by default when using the `/api/node/health` handler. Unfortunately that handler is only available for solr 8+, so we will likely need a parameter in the CRD that allows for a backwards compatible health  check endpoint.

**Comment by HoustonPutman** [comment]
Also sorry for missing your previous question, I thought I had responded. Since we are using a StatefulSet, there should be downtime unfortunately. Though we could definitely add in our own magic to make that work. I think we need some architectural discussions around upgrades/rolling restarts in general.
