### ISSUE TITLE
Add new solr collection resource type

### ISSUE THREAD

**Issue by AceHack** [bloomberg/solr-operator#7]
Add ability for the operator to create solr collections

**Comment by HoustonPutman** [comment]
Hey Aaron, thanks for reaching out.

So far the operator only really manages solr nodes. Solr has a CollectionsApi to manage collections, so I would imagine that this would just be a wrapper to call that endpoint. What additional features would you want from a Collection CRD?

**Comment by AceHack** [comment]
The ability to backup and restore collections, the ability to split shards when scaling out, the proper management of ensuring shards are spread across availability zones, just to name a few.

Thanks for the awesome operator.

**Comment by HoustonPutman** [comment]
I think that's a good point with availability zones and shard splitting, etc. And it would definitely allow for better horizontal scaling (as mentioned in Phase V Auto Pilot, from you other issue).

I'm currently working on the backup and metrics collector CRDs, but I'll loop back around to this after that. Feel free to take a stab and create a PR though!

I do imagine that this CRD would change what the backup CRD would look like, but we can cross that bridge when we get to it.

**Comment by AceHack** [comment]
One other feature I would like is a CollectionShardDisruptionBudget.  It would work just like a PodDisriuptionBudget but when draining a node it would make sure at most only x replicas are down for any collection shard.

**Comment by HoustonPutman** [comment]
I definitely agree. Would you make a separate PR for that? Cause PodDisruptionBudgets need to be supported as well.

**Comment by sepulworld** [comment]
I can take a stab at creating the Collection CRD.

**Comment by sepulworld** [comment]
Initial feature CRD for collections setup and tested here https://github.com/bloomberg/solr-operator/pull/17

**Comment by sepulworld** [comment]
We can probably close this now. Initial support in place for collections CRD.
