### ISSUE TITLE
Have the Solr Operator auto-register all Solr CRDs

### ISSUE THREAD

**Issue by HoustonPutman** [bloomberg/solr-operator#9]
Currently the operator requires you to have already registered your Solr CRDs in Kubernetes. It would be nice if the operator could load in the Solr CRDs that are not already registered.

**Comment by sepulworld** [comment]
I was thinking about this the other day after reading this blog: https://medium.com/@cloudark/kubernetes-operators-and-helm-it-takes-two-to-tango-3ff6dcf65619

Might be worth reconsidering the path of auto registering and instead focus on getting a solid Helm chart https://github.com/bloomberg/solr-operator/issues/20 out there.

**Comment by HoustonPutman** [comment]
Agreed with @sepulworld. Now that we have a version of the helm chart for each version of the operator (going forward), this is no longer necessary.
